name: newsbuzz
description: Daily News

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  share: '0.5.3'
  flutter_webview_plugin: '0.2.1+2'
  google_sign_in: '3.2.2'
  firebase_analytics: '1.0.4'
  firebase_auth: '0.6.2+1'
  firebase_database: '1.0.5'
  firebase_storage: '1.0.4'
  timeago: '2.0.8'
  cupertino_icons: '0.1.2'

flutter:
  uses-material-design: true
